#!/bin/bash

#PATH=~/bin:/Applications/Aquamacs\ Emacs.app/Contents/MacOS/bin:$PATH
PATH=~/bin:~/Applications/Emacs.app/Contents/MacOS/bin:$PATH

if [ ${DISPLAY:-unset} = unset ]
then
    exec vi ${1+"$@"}
fi

case $(basename $0) in
    editwait)
        _editor='emacsclient'
        ;;
    editin)
        #_editor='emacsclient -c'  # emacs 23
        _editor='emacsclient'
        ;;
    *)
        #_editor='emacsclient -c -n'  # emacs 23
        _editor='emacsclient -n'
esac

ALTERNATE_EDITOR=edit-client.xemacs
if emacsclient -e t >/dev/null 2>&1;
then
    exec $_editor ${1+"$@"}
else
    emacs-server &
    until emacsclient -e t >/dev/null 2>&1
    do
        sleep 1
    done
    exec $_editor ${1+"$@"}
fi

