#!/bin/bash

PATH=~/bin:/Applications/Emacs.app/Contents/MacOS/bin:$PATH

if [[ $(uname -s) != "Darwin" ]]; then
    if [ ${DISPLAY:-unset} = unset ]; then
      exec vi ${1+"$@"}
    fi
fi

case $(basename $0) in
    editwait)
        _editor='emacsclient'
        ;;
    editin)
        _editor='emacsclient -c'
        ;;
    *)
        _editor='emacsclient -c -n'
esac

ALTERNATE_EDITOR=vi

if emacsclient -e t >/dev/null 2>&1;
then
    exec $_editor ${1+"$@"}
else
    emacs-server &
    until emacsclient -e t >/dev/null 2>&1
    do
        sleep 1
    done
    exec $_editor ${1+"$@"}
fi

